### ISSUE TITLE
[Bug] Fast game mode is not fast and Custom mode settings doesn't apply to Custom mode

### ISSUE THREAD

**Issue by mngweb** [Nefariusek/CodersCamp2021.Project.Typescript.Coderscassonne#107]
**Description**

**Steps to reproduce**
1. Go to Settings page
2. Click 'Fast mode' or 'Custom mode'
3. Play game
4. Note that it's like Classic game

**Desired functionality**
Fast mode game as in Fast mode description

**Additional informations**

**Comment by Urszuja** [comment]
fast game and custom game modes will be temporaly removed for purpose of presentation.
