### ISSUE TITLE
[Bug] 'Tiles left' always shows 2 less tiles than they actually are

### ISSUE THREAD

**Issue by mngweb** [Nefariusek/CodersCamp2021.Project.Typescript.Coderscassonne#134]
**Steps to reproduce**
1. Play game to see Gameboard
2. Look at the bottom at 'Tiles left'
3. Note that it always shows 2 less tiles than they actually are

**Desired functionality**
'Tiles left' should show as many tiles as there are actually in drawPile.

**Comment by Urszuja** [comment]
1. one tile is placed as starting tile.
2. one tile is in hand
3. left tiles shows all tiles - starting tile - placed tiles - tile in hand

**Comment by Urszuja** [comment]
done.
